// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dwinanda09/forte-commerce/internal/domain (interfaces: CampaignRepository)
//
// Generated by this command:
//
//	mockgen -destination=/Users/dwinanda/saas/fortecommerce/backend/internal/mocks/campaign_repo_mock.go -package=mocks github.com/dwinanda09/forte-commerce/internal/domain CampaignRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dwinanda09/forte-commerce/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCampaignRepository is a mock of CampaignRepository interface.
type MockCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockCampaignRepositoryMockRecorder is the mock recorder for MockCampaignRepository.
type MockCampaignRepositoryMockRecorder struct {
	mock *MockCampaignRepository
}

// NewMockCampaignRepository creates a new mock instance.
func NewMockCampaignRepository(ctrl *gomock.Controller) *MockCampaignRepository {
	mock := &MockCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignRepository) EXPECT() *MockCampaignRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCampaignRepository) Create(ctx context.Context, c *domain.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCampaignRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCampaignRepository)(nil).Create), ctx, c)
}

// Delete mocks base method.
func (m *MockCampaignRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCampaignRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCampaignRepository)(nil).Delete), ctx, id)
}

// FindActive mocks base method.
func (m *MockCampaignRepository) FindActive(ctx context.Context) ([]domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActive", ctx)
	ret0, _ := ret[0].([]domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActive indicates an expected call of FindActive.
func (mr *MockCampaignRepositoryMockRecorder) FindActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActive", reflect.TypeOf((*MockCampaignRepository)(nil).FindActive), ctx)
}

// FindAll mocks base method.
func (m *MockCampaignRepository) FindAll(ctx context.Context) ([]domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCampaignRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCampaignRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockCampaignRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCampaignRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCampaignRepository)(nil).FindByID), ctx, id)
}

// Toggle mocks base method.
func (m *MockCampaignRepository) Toggle(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Toggle", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// Toggle indicates an expected call of Toggle.
func (mr *MockCampaignRepositoryMockRecorder) Toggle(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggle", reflect.TypeOf((*MockCampaignRepository)(nil).Toggle), ctx, id, active)
}

// Update mocks base method.
func (m *MockCampaignRepository) Update(ctx context.Context, c *domain.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCampaignRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCampaignRepository)(nil).Update), ctx, c)
}
