// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dwinanda09/forte-commerce/internal/domain (interfaces: CheckoutRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/checkout_repo_mock.go -package=mocks github.com/dwinanda09/forte-commerce/internal/domain CheckoutRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dwinanda09/forte-commerce/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckoutRepository is a mock of CheckoutRepository interface.
type MockCheckoutRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckoutRepositoryMockRecorder is the mock recorder for MockCheckoutRepository.
type MockCheckoutRepositoryMockRecorder struct {
	mock *MockCheckoutRepository
}

// NewMockCheckoutRepository creates a new mock instance.
func NewMockCheckoutRepository(ctrl *gomock.Controller) *MockCheckoutRepository {
	mock := &MockCheckoutRepository{ctrl: ctrl}
	mock.recorder = &MockCheckoutRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutRepository) EXPECT() *MockCheckoutRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckoutRepository) Create(ctx context.Context, session *domain.CheckoutSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCheckoutRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckoutRepository)(nil).Create), ctx, session)
}

// FindByID mocks base method.
func (m *MockCheckoutRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCheckoutRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCheckoutRepository)(nil).FindByID), ctx, id)
}

// FindExpiredPending mocks base method.
func (m *MockCheckoutRepository) FindExpiredPending(ctx context.Context) ([]domain.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiredPending", ctx)
	ret0, _ := ret[0].([]domain.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiredPending indicates an expected call of FindExpiredPending.
func (mr *MockCheckoutRepositoryMockRecorder) FindExpiredPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiredPending", reflect.TypeOf((*MockCheckoutRepository)(nil).FindExpiredPending), ctx)
}

// UpdateStatus mocks base method.
func (m *MockCheckoutRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.CheckoutStatus, result []byte, errMsg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, result, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCheckoutRepositoryMockRecorder) UpdateStatus(ctx, id, status, result, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCheckoutRepository)(nil).UpdateStatus), ctx, id, status, result, errMsg)
}
