// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dwinanda09/forte-commerce/internal/domain (interfaces: ProductRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/product_repo_mock.go -package=mocks github.com/dwinanda09/forte-commerce/internal/domain ProductRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dwinanda09/forte-commerce/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductRepository) Create(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryMockRecorder) Create(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepository)(nil).Create), ctx, product)
}

// DecrementInventory mocks base method.
func (m *MockProductRepository) DecrementInventory(ctx context.Context, sku string, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementInventory", ctx, sku, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementInventory indicates an expected call of DecrementInventory.
func (mr *MockProductRepositoryMockRecorder) DecrementInventory(ctx, sku, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementInventory", reflect.TypeOf((*MockProductRepository)(nil).DecrementInventory), ctx, sku, qty)
}

// DecrementReserved mocks base method.
func (m *MockProductRepository) DecrementReserved(ctx context.Context, sku string, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementReserved", ctx, sku, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementReserved indicates an expected call of DecrementReserved.
func (mr *MockProductRepositoryMockRecorder) DecrementReserved(ctx, sku, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementReserved", reflect.TypeOf((*MockProductRepository)(nil).DecrementReserved), ctx, sku, qty)
}

// Delete mocks base method.
func (m *MockProductRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockProductRepository) FindAll(ctx context.Context) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockProductRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockProductRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockProductRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductRepository)(nil).FindByID), ctx, id)
}

// FindBySKU mocks base method.
func (m *MockProductRepository) FindBySKU(ctx context.Context, sku string) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySKU", ctx, sku)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySKU indicates an expected call of FindBySKU.
func (mr *MockProductRepositoryMockRecorder) FindBySKU(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySKU", reflect.TypeOf((*MockProductRepository)(nil).FindBySKU), ctx, sku)
}

// FindBySKUs mocks base method.
func (m *MockProductRepository) FindBySKUs(ctx context.Context, skus []string) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySKUs", ctx, skus)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySKUs indicates an expected call of FindBySKUs.
func (mr *MockProductRepositoryMockRecorder) FindBySKUs(ctx, skus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySKUs", reflect.TypeOf((*MockProductRepository)(nil).FindBySKUs), ctx, skus)
}

// IncrementReserved mocks base method.
func (m *MockProductRepository) IncrementReserved(ctx context.Context, sku string, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementReserved", ctx, sku, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementReserved indicates an expected call of IncrementReserved.
func (mr *MockProductRepositoryMockRecorder) IncrementReserved(ctx, sku, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementReserved", reflect.TypeOf((*MockProductRepository)(nil).IncrementReserved), ctx, sku, qty)
}

// RestoreInventory mocks base method.
func (m *MockProductRepository) RestoreInventory(ctx context.Context, sku string, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreInventory", ctx, sku, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreInventory indicates an expected call of RestoreInventory.
func (mr *MockProductRepositoryMockRecorder) RestoreInventory(ctx, sku, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreInventory", reflect.TypeOf((*MockProductRepository)(nil).RestoreInventory), ctx, sku, qty)
}

// Update mocks base method.
func (m *MockProductRepository) Update(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductRepositoryMockRecorder) Update(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductRepository)(nil).Update), ctx, product)
}
