// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dwinanda09/forte-commerce/internal/domain (interfaces: PromotionEngine)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/promotion_engine_mock.go -package=mocks github.com/dwinanda09/forte-commerce/internal/domain PromotionEngine
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dwinanda09/forte-commerce/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPromotionEngine is a mock of PromotionEngine interface.
type MockPromotionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionEngineMockRecorder
	isgomock struct{}
}

// MockPromotionEngineMockRecorder is the mock recorder for MockPromotionEngine.
type MockPromotionEngineMockRecorder struct {
	mock *MockPromotionEngine
}

// NewMockPromotionEngine creates a new mock instance.
func NewMockPromotionEngine(ctrl *gomock.Controller) *MockPromotionEngine {
	mock := &MockPromotionEngine{ctrl: ctrl}
	mock.recorder = &MockPromotionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionEngine) EXPECT() *MockPromotionEngineMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockPromotionEngine) Apply(ctx context.Context, cart map[string]*domain.CartItem) ([]domain.AppliedPromotion, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, cart)
	ret0, _ := ret[0].([]domain.AppliedPromotion)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Apply indicates an expected call of Apply.
func (mr *MockPromotionEngineMockRecorder) Apply(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockPromotionEngine)(nil).Apply), ctx, cart)
}
