// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/queue.go -destination=internal/mocks/queue_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	amqp091 "github.com/rabbitmq/amqp091-go"
	gomock "go.uber.org/mock/gomock"
)

// MockQueuePublisher is a mock of QueuePublisher interface.
type MockQueuePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockQueuePublisherMockRecorder
	isgomock struct{}
}

// MockQueuePublisherMockRecorder is the mock recorder for MockQueuePublisher.
type MockQueuePublisherMockRecorder struct {
	mock *MockQueuePublisher
}

// NewMockQueuePublisher creates a new mock instance.
func NewMockQueuePublisher(ctrl *gomock.Controller) *MockQueuePublisher {
	mock := &MockQueuePublisher{ctrl: ctrl}
	mock.recorder = &MockQueuePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueuePublisher) EXPECT() *MockQueuePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockQueuePublisher) Publish(ctx context.Context, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockQueuePublisherMockRecorder) Publish(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockQueuePublisher)(nil).Publish), ctx, body)
}

// MockQueueConsumer is a mock of QueueConsumer interface.
type MockQueueConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockQueueConsumerMockRecorder
	isgomock struct{}
}

// MockQueueConsumerMockRecorder is the mock recorder for MockQueueConsumer.
type MockQueueConsumerMockRecorder struct {
	mock *MockQueueConsumer
}

// NewMockQueueConsumer creates a new mock instance.
func NewMockQueueConsumer(ctrl *gomock.Controller) *MockQueueConsumer {
	mock := &MockQueueConsumer{ctrl: ctrl}
	mock.recorder = &MockQueueConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueConsumer) EXPECT() *MockQueueConsumerMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockQueueConsumer) Consume() (<-chan amqp091.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume")
	ret0, _ := ret[0].(<-chan amqp091.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockQueueConsumerMockRecorder) Consume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockQueueConsumer)(nil).Consume))
}
